
IMAGE_PLOT_X_MIN = -3.0
IMAGE_PLOT_X_MAX = 3.0
IMAGE_PLOT_Y_MIN = -3.0
IMAGE_PLOT_Y_MAX = 3.0

CENTROIDS_DIRECTORY = 'data/centroids/'
HIDDEN_MARKOV_MODE_DIRECTORY = 'data/hmm/'
HIDDEN_MARKOV_MODEL_VERBOSE = True

PEN_DOWN_LABEL_DELTA = 3
PEN_UP_LABEL_DELTA = 2
STOP_LABEL_DELTA = 1

MAX_SAMPLE_LENGTH = 500
