
IMAGE_PLOT_X_MIN = -3.0
IMAGE_PLOT_X_MAX = 3.0
IMAGE_PLOT_Y_MIN = -3.0
IMAGE_PLOT_Y_MAX = 3.0

N_OBSERVATION_CLASSES = 256
CENTROIDS_FILENAME = 'data/centroids.dat'

N_HIDDEN_MARKOV_MODEL_STATES = 10
